# Generated by Django 4.2.16 on 2024-11-19 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_category_options_alter_listing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['date_joined'], 'verbose_name': 'Marketplace_User', 'verbose_name_plural': 'Marketplace_Users'},
        ),
    ]
